### ISSUE TITLE
[ERROR] Update isn't possible in Juno

### ISSUE THREAD

**Issue by btd1337** [mdh34/quickDocs#39]
com.github.mdh34.quickdocs:
 Depends: libdevhelp-3-2 (>=3.7.91) but it is not installable

but it is installed:

![captura de tela de 2018-05-26 20-44-05](https://user-images.githubusercontent.com/11943860/40581079-a52dbd36-6125-11e8-9fce-174cbdaeaa7b.png)

![captura de tela de 2018-05-26 20-45-18](https://user-images.githubusercontent.com/11943860/40581084-b8f2d6c6-6125-11e8-9942-8625f93c9a8c.png)

**Comment by mdh34** [comment]
18.04 comes with a newer version of libdevhelp (3-5) which isn't compatible with the version 16.04 had (3-2). Because the quickDocs package is built for 16.04 because of appcenter, apt won't upgrade between these incompatible library versions.

This isn't a problem specific to quickDocs (lots of granite apps don't work because of the older version of granite) - once  appcenter starts adding bionic builds to their repos this shouldn't be a problem anymore

**Comment by mdh34** [comment]
I'm closing this because at the moment it's beyond my control
